#include<algorithm>
#include<cctype>
#include<chrono>//poj不能用
#include<cmath>
#include<cstdio>
#include<cstring>
#include<functional>
#include<iomanip>
#include<iostream>
#include<map>
#include<queue>
#include<random>//poj不能用
#include<set>
#include<sstream>
#include<stack>
#include<string>
#include<utility>
#include<vector>